.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/

variables:
  OUTPUT_NAME: uniovi-localize-me

stages:
  - lint
  - build
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - if: '$CI_COMMIT_REF_SLUG == "main"'
      when: always
    - when: never

lint-backend:
  image: cafeteru/localize-me-backend
  stage: lint
  extends: .go-cache
  script:
    - cd backend && golangci-lint run -v

lint-frontend:
  image: cafeteru/node-chrome-headless
  stage: lint
  script:
    - cd frontend && npm install && npm run lint

build-backend:
  image: cafeteru/localize-me-backend
  stage: build
  extends: .go-cache
  script:
    - cd backend && go build -race -o $OUTPUT_NAME
  artifacts:
    paths:
      - $OUTPUT_NAME

test-backend:
  image: cafeteru/localize-me-backend
  stage: test
  extends: .go-cache
  script:
    - cd backend && gotestsum --junitfile ../report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

test-frontend:
  image: cafeteru/node-chrome-headless
  stage: test
  script:
    - cd frontend && npm install && npm run unit-test
