services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
  
  mongo-seed:
    container_name: mongo-seed
    build: ./mongo-seed
    depends_on:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    entrypoint: ["/bin/bash", "/mongo-seed/start.sh"]

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./backend:/backend
    depends_on:
      - mongo
    environment:
      ATLAS_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    environment:
      urlApi: "http://backend"

  spotiapp:
    container_name: spotiapp
    image: cafeteru/localize-me-spotiapp:latest
    ports:
      - "90:80"
    volumes:
      - ./:/spotiapp
    depends_on:
      - backend
    environment:
      urlApi: "http://backend"

volumes:
  mongo_data:
