services:
  database:
    container_name: localize-me-database
    build:
      context: ./database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-volume:/data/db

  backend:
    container_name: localize-me-backend
    build: ./backend
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    environment:
      ATLAS_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017

  frontend:
    container_name: localize-me-frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    environment:
      urlApi: 'http://backend'

  spotiapp:
    container_name: localize-me-spotiapp
    image: cafeteru/localize-me-spotiapp:latest
    ports:
      - "90:80"
    volumes:
      - ./:/spotiapp
    depends_on:
      - backend
    environment:
      urlApi: 'http://backend'
