version: '3.8'

services:
  database:
    container_name: localize-me-database
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - localize-me-network
  mongo-seed:
    container_name: localize-me-mongo-seed
    image: mongo:latest
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./mongo-seed:/mongo-seed
    command: bash "mongo-seed/import.sh"
    networks:
      - localize-me-network
  backend:
    container_name: localize-me-backend
    image: cafeteru/localize-me-backend:latest
    command: bash "scripts/docker.sh"
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./:/backend
    depends_on:
      - database
    networks:
      - localize-me-network
    environment:
      ATLAS_URI: mongodb://mongoadmin:secret@database:27017
  frontend:
    container_name: localize-me-frontend
    image: cafeteru/localize-me-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./:/frontend
    depends_on:
      - backend
    networks:
      - localize-me-network
    environment:
      urlApi: 'http://backend'
  spotiapp:
    container_name: localize-me-spotiapp
    image: cafeteru/localize-me-spotiapp:latest
    ports:
      - "90:80"
    volumes:
      - ./:/spotiapp
    depends_on:
      - backend
    networks:
      - localize-me-network
    environment:
      urlApi: 'http://backend'

networks:
  localize-me-network:
    name: localize-me-network
    driver: bridge
