package constants

const (
	CreateConnection        = "starting the connection"
	DataLogin               = "data invalid"
	DeleteGroup             = "error delete group"
	DeleteLanguage          = "error delete language"
	DeleteStage             = "error delete stage"
	DeleteUser              = "error delete user"
	EmailAlreadyRegister    = "email already registered"
	EncryptPasswordUser     = "encrypting password"
	FindGroupById           = "no found group by id"
	FindGroupByName         = "no found group by name"
	FindLanguageById        = "no found language by id"
	FindLanguageByIsoCode   = "no found language by isoCode"
	FindStageById           = "no found stage by id"
	FindStageByName         = "no found stage by name"
	FindUserByEmail         = "no found user by email"
	FindUserById            = "no found user by id"
	GroupAlreadyRegister    = "group already registered"
	GroupNotHavePermissions = "user have not permissions to update the group"
	IdNoValid               = "id no valid"
	InsertGroup             = "insert group"
	InsertLanguage          = "insert language"
	InsertStage             = "insert stage"
	InsertUser              = "insert user"
	InvalidUserRequest      = "userRequest no valid"
	IsoCodeLanguageInvalid  = "language's isoCode invalid"
	LanguageAlreadyRegister = "language already registered"
	NameGroupInvalid        = "group's name invalid"
	NameStageInvalid        = "stage's name invalid"
	ReadDatabase            = "problems reading data from database"
	StageAlreadyRegister    = "stage already registered"
	UpdateLanguage          = "updating language"
	UpdateStage             = "updating stage"
	UpdateUser              = "updating user"
	UserNoActive            = "user no active"
	UserNoAdmin             = "user no admin"
	UserNoRegister          = "user no register"
)
