// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/StageRepository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/HP-SCDS/Observatorio/2021-2022/localizeme/uniovi-localizeme/internal/core/domain"
	mongo "go.mongodb.org/mongo-driver/mongo"
)

// MockStageRepository is a mock of StageRepository interface.
type MockStageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStageRepositoryMockRecorder
}

// MockStageRepositoryMockRecorder is the mock recorder for MockStageRepository.
type MockStageRepositoryMockRecorder struct {
	mock *MockStageRepository
}

// NewMockStageRepository creates a new mock instance.
func NewMockStageRepository(ctrl *gomock.Controller) *MockStageRepository {
	mock := &MockStageRepository{ctrl: ctrl}
	mock.recorder = &MockStageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStageRepository) EXPECT() *MockStageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStageRepository) Create(user domain.Stage) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStageRepositoryMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStageRepository)(nil).Create), user)
}

// FindByName mocks base method.
func (m *MockStageRepository) FindByName(name string) (*domain.Stage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(*domain.Stage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockStageRepositoryMockRecorder) FindByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockStageRepository)(nil).FindByName), name)
}
