name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy-on-Docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Backend Docker image
      run: |
        docker build -t localize-me-backend backend/.
        docker tag localize-me-backend cafeteru/localize-me-backend:latest
        docker push cafeteru/localize-me-backend:latest

    - name: Build the Frontend Docker image
      run: |
        docker build -t localize-me-frontend frontend/.
        docker tag localize-me-frontend cafeteru/localize-me-frontend:latest
        docker push cafeteru/localize-me-frontend:latest
        
    - name: Build the Spotiapp Docker image
      run: |
        docker build -t localize-me-spotiapp spotiapp/.
        docker tag localize-me-spotiapp cafeteru/localize-me-spotiapp:latest
        docker push cafeteru/localize-me-spotiapp:latest
