name: Frontend Actions
run-name: ${{ github.actor }} is checking frontend 🪟
on: [push]
jobs:
  frontend:
    runs-on: ubuntu-latest
    container: cafeteru/node-maven-selenium

    steps:
      - uses: actions/checkout@master
      
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: frontend
        run: yarn

      - name: Execute tests
        working-directory: frontend
        run: |
          yarn run unit-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            directory: ./frontend/coverage/report-cobertura
            fail_ci_if_error: true
            flags: frontend