name: Frontend Actions
run-name: ${{ github.actor }} is checking frontend 🚀
on: [push]
jobs:
  frontend:
    runs-on: ubuntu-latest
    container: 
      image: cafeteru/node-chrome-headless
      credentials:
         username: ${{ github.ref }}
         password: ${{ secrets.GITHUB_TOKEN }}
      env: 
        actor: ${{ github.actor }}
        testjob: here is value
    steps:
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Check lint code
        working-directory: frontend
        run: npm run lint

